name: Updates CI
on:
  repository_dispatch:
    types: [ updates ]
  workflow_dispatch:
jobs:
  release:
    name: Deploy updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - name: Update code
        uses: Neidn/uptime-monitor-by-golang@main
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
